eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: lost-and-found-service