eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
    instance:
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80
    hostname: ${DOMAIN_NAME}
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}
spring:
  profiles: heroku

  