eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:localhost:5000}/eureka/
    instance:
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80
    hostname: ${DOMAIN_NAME}
  instance:
      instanceId: ${DOMAIN_NAME}
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}
