eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000}/eureka/
  instance:
      instanceId: ${DOMAIN_NAME:lostAndFound}:${random.value}
      hostname: ${DOMAIN_NAME:lostAndFound}
      nonSecurePort: 80