eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    instanceId: https://propets-lostandfoundservice.herokuapp.com/
  password: ${USER_PASSWORD:password}